export * as age from "./ic_age.png";
export * as appointments from "./ic_appointments.png";
export * as bell from "./ic_bell.png";
export * as breed from "./ic_breed.png";
export * as calendar from "./ic_calendar.png";
export * as consultation from "./ic_consultation.png";
export * as contacts from "./ic_contacts.png";
export * as d_chevron from "./ic_d_chevron.png";
export * as dataAnalytics from "./ic_data analytics.png";
export * as dotsVertical from "./ic_dots-vertical.png";
export * as helpCenter from "./ic_help center.png";
export * as home from "./ic_home-02.png";
export * as l_chevron from "./ic_l_chevron.png";
export * as messages from "./ic_messages.png";
export * as parkOutlineInjection from "./ic_park-outline_injection.png";
export * as phone from "./ic_phone.png";
export * as pin from "./ic_pin.png";
export * as r_chevron from "./ic_r_chevron.png";
export * as searchLg from "./ic_search-lg.png";
export * as settings from "./ic_settings.png";
export * as sex from "./ic_sex.png";
export * as signOut from "./ic_sign out.png";
export * as subscription from "./ic_subscription.png";
export * as user from "./ic_user.png";
export * as vector from "./Vector.png";
export * as logo from "./logo.png";
export * as rightSideBarArrow from "./ic_double chevron_right.png";
export * as leftSideBarArrow from "./ic_double chevron _left.png";
export * as userAvatar from "./Frame 9.png";
export * as clientAvatar from "./Frame 13.png";
export * as clientDetailsAvatar from "./Frame 14.png";
export * as carti from "./carti.jpg";
